//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finder.Bot.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminLocale {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminLocale() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Finder.Bot.Resources.AdminLocale", typeof(AdminLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AdminError_purge {
            get {
                return ResourceManager.GetString("AdminError_purge", resourceCulture);
            }
        }
        
        internal static string AdminError_slowmodeNegative {
            get {
                return ResourceManager.GetString("AdminError_slowmodeNegative", resourceCulture);
            }
        }
        
        internal static string AdminEmbedSlowmode_title {
            get {
                return ResourceManager.GetString("AdminEmbedSlowmode_title", resourceCulture);
            }
        }
        
        internal static string AdminEmbedSlowmode_field0Name {
            get {
                return ResourceManager.GetString("AdminEmbedSlowmode_field0Name", resourceCulture);
            }
        }
        
        internal static string AdminEmbedSlowmode_field1Name {
            get {
                return ResourceManager.GetString("AdminEmbedSlowmode_field1Name", resourceCulture);
            }
        }
        
        internal static string AdminEmbedSlowmode_field2Name {
            get {
                return ResourceManager.GetString("AdminEmbedSlowmode_field2Name", resourceCulture);
            }
        }
        
        internal static string AdminEmbedLockdown_title {
            get {
                return ResourceManager.GetString("AdminEmbedLockdown_title", resourceCulture);
            }
        }
        
        internal static string AdminEmbedLockdown_field0Name {
            get {
                return ResourceManager.GetString("AdminEmbedLockdown_field0Name", resourceCulture);
            }
        }
        
        internal static string AdminEmbedLockdown_field1Name {
            get {
                return ResourceManager.GetString("AdminEmbedLockdown_field1Name", resourceCulture);
            }
        }
    }
}
