//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finder.Bot.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CountdownLocale {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountdownLocale() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Finder.Bot.Resources.CountdownLocale", typeof(CountdownLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CountdownError_invalid {
            get {
                return ResourceManager.GetString("CountdownError_invalid", resourceCulture);
            }
        }
        
        internal static string CountdownError_past {
            get {
                return ResourceManager.GetString("CountdownError_past", resourceCulture);
            }
        }
        
        internal static string CountdownError_future {
            get {
                return ResourceManager.GetString("CountdownError_future", resourceCulture);
            }
        }
        
        internal static string CountdownError_ping {
            get {
                return ResourceManager.GetString("CountdownError_ping", resourceCulture);
            }
        }
        
        internal static string CountdownEmbed_title {
            get {
                return ResourceManager.GetString("CountdownEmbed_title", resourceCulture);
            }
        }
        
        internal static string CountdownEmbed_fieldName {
            get {
                return ResourceManager.GetString("CountdownEmbed_fieldName", resourceCulture);
            }
        }
        
        internal static string CountdownEmbed_fieldValue {
            get {
                return ResourceManager.GetString("CountdownEmbed_fieldValue", resourceCulture);
            }
        }
        
        internal static string CountdownEmbed_fieldValueEnd {
            get {
                return ResourceManager.GetString("CountdownEmbed_fieldValueEnd", resourceCulture);
            }
        }
        
        internal static string CountdownDays {
            get {
                return ResourceManager.GetString("CountdownDays", resourceCulture);
            }
        }
        
        internal static string CountdownHours {
            get {
                return ResourceManager.GetString("CountdownHours", resourceCulture);
            }
        }
        
        internal static string CountdownMins {
            get {
                return ResourceManager.GetString("CountdownMins", resourceCulture);
            }
        }
        
        internal static string CountdownSecs {
            get {
                return ResourceManager.GetString("CountdownSecs", resourceCulture);
            }
        }
        
        internal static string CountdownSingular {
            get {
                return ResourceManager.GetString("CountdownSingular", resourceCulture);
            }
        }
        
        internal static string CountdownPlural {
            get {
                return ResourceManager.GetString("CountdownPlural", resourceCulture);
            }
        }
        
        internal static string CountdownSeperator {
            get {
                return ResourceManager.GetString("CountdownSeperator", resourceCulture);
            }
        }
        
        internal static string CountdownPing {
            get {
                return ResourceManager.GetString("CountdownPing", resourceCulture);
            }
        }
    }
}
