//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finder.Bot.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EconomyLocale {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EconomyLocale() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Finder.Bot.Resources.EconomyLocale", typeof(EconomyLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EconomyEmbedBal_title {
            get {
                return ResourceManager.GetString("EconomyEmbedBal_title", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedBal_field0Name {
            get {
                return ResourceManager.GetString("EconomyEmbedBal_field0Name", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedBal_field1Name {
            get {
                return ResourceManager.GetString("EconomyEmbedBal_field1Name", resourceCulture);
            }
        }
        
        internal static string EconomyError_notEnoughMoney {
            get {
                return ResourceManager.GetString("EconomyError_notEnoughMoney", resourceCulture);
            }
        }
        
        internal static string EconomyError_notEnoughMoneyBank {
            get {
                return ResourceManager.GetString("EconomyError_notEnoughMoneyBank", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedDeposit_title {
            get {
                return ResourceManager.GetString("EconomyEmbedDeposit_title", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedDeposit_fieldName {
            get {
                return ResourceManager.GetString("EconomyEmbedDeposit_fieldName", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedWithdraw_title {
            get {
                return ResourceManager.GetString("EconomyEmbedWithdraw_title", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedWithdraw_fieldName {
            get {
                return ResourceManager.GetString("EconomyEmbedWithdraw_fieldName", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedPay_title {
            get {
                return ResourceManager.GetString("EconomyEmbedPay_title", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedPay_field0Name {
            get {
                return ResourceManager.GetString("EconomyEmbedPay_field0Name", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedPay_field1Name {
            get {
                return ResourceManager.GetString("EconomyEmbedPay_field1Name", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedTransfer_title {
            get {
                return ResourceManager.GetString("EconomyEmbedTransfer_title", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedTransfer_field0Name {
            get {
                return ResourceManager.GetString("EconomyEmbedTransfer_field0Name", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedTransfer_field1Name {
            get {
                return ResourceManager.GetString("EconomyEmbedTransfer_field1Name", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedSetBal_title {
            get {
                return ResourceManager.GetString("EconomyEmbedSetBal_title", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedSetBal_field1Name {
            get {
                return ResourceManager.GetString("EconomyEmbedSetBal_field1Name", resourceCulture);
            }
        }
        
        internal static string EconomyEmbedSetBal_field0Name {
            get {
                return ResourceManager.GetString("EconomyEmbedSetBal_field0Name", resourceCulture);
            }
        }
    }
}
