//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finder.Bot.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LevelingLocale {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LevelingLocale() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Finder.Bot.Resources.LevelingLocale", typeof(LevelingLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LevelingEmbedLevel_title {
            get {
                return ResourceManager.GetString("LevelingEmbedLevel_title", resourceCulture);
            }
        }
        
        internal static string LevelingEmbedLevel_field0Name {
            get {
                return ResourceManager.GetString("LevelingEmbedLevel_field0Name", resourceCulture);
            }
        }
        
        internal static string LevelingEmbedLevel_field1Name {
            get {
                return ResourceManager.GetString("LevelingEmbedLevel_field1Name", resourceCulture);
            }
        }
        
        internal static string LevelingEmbedLvlUp_title {
            get {
                return ResourceManager.GetString("LevelingEmbedLvlUp_title", resourceCulture);
            }
        }
        
        internal static string LevelingEmbedLvlUp_fieldName {
            get {
                return ResourceManager.GetString("LevelingEmbedLvlUp_fieldName", resourceCulture);
            }
        }
    }
}
