//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finder.Bot.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModerationLocale {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModerationLocale() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Finder.Bot.Resources.ModerationLocale", typeof(ModerationLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ModerationEmbedBan_title {
            get {
                return ResourceManager.GetString("ModerationEmbedBan_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbed_fieldReasonValue {
            get {
                return ResourceManager.GetString("ModerationEmbed_fieldReasonValue", resourceCulture);
            }
        }
        
        internal static string ModerationEmbed_fieldReasonName {
            get {
                return ResourceManager.GetString("ModerationEmbed_fieldReasonName", resourceCulture);
            }
        }
        
        internal static string ModerationEmbed_fieldUserValue {
            get {
                return ResourceManager.GetString("ModerationEmbed_fieldUserValue", resourceCulture);
            }
        }
        
        internal static string ModerationEmbed_fieldUserName {
            get {
                return ResourceManager.GetString("ModerationEmbed_fieldUserName", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedKick_title {
            get {
                return ResourceManager.GetString("ModerationEmbedKick_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedWarn_title {
            get {
                return ResourceManager.GetString("ModerationEmbedWarn_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedMute_title {
            get {
                return ResourceManager.GetString("ModerationEmbedMute_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedBanned_title {
            get {
                return ResourceManager.GetString("ModerationEmbedBanned_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedBannedDM_title {
            get {
                return ResourceManager.GetString("ModerationEmbedBannedDM_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbed_fieldServerName {
            get {
                return ResourceManager.GetString("ModerationEmbed_fieldServerName", resourceCulture);
            }
        }
        
        internal static string ModerationEmbed_fieldServerValue {
            get {
                return ResourceManager.GetString("ModerationEmbed_fieldServerValue", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedKicked_title {
            get {
                return ResourceManager.GetString("ModerationEmbedKicked_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedKickedDM_title {
            get {
                return ResourceManager.GetString("ModerationEmbedKickedDM_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedWarned_title {
            get {
                return ResourceManager.GetString("ModerationEmbedWarned_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedWarnedDM_title {
            get {
                return ResourceManager.GetString("ModerationEmbedWarnedDM_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedMuted_title {
            get {
                return ResourceManager.GetString("ModerationEmbedMuted_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedMutedDM_title {
            get {
                return ResourceManager.GetString("ModerationEmbedMutedDM_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedUnmute_title {
            get {
                return ResourceManager.GetString("ModerationEmbedUnmute_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedUnmutedDM_title {
            get {
                return ResourceManager.GetString("ModerationEmbedUnmutedDM_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedUnmuted_title {
            get {
                return ResourceManager.GetString("ModerationEmbedUnmuted_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedUnbanned_title {
            get {
                return ResourceManager.GetString("ModerationEmbedUnbanned_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedUnbannedDM_title {
            get {
                return ResourceManager.GetString("ModerationEmbedUnbannedDM_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedUnban_title {
            get {
                return ResourceManager.GetString("ModerationEmbedUnban_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbed_fieldTimeName {
            get {
                return ResourceManager.GetString("ModerationEmbed_fieldTimeName", resourceCulture);
            }
        }
        
        internal static string ModerationEmbed_fieldTimeValue {
            get {
                return ResourceManager.GetString("ModerationEmbed_fieldTimeValue", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedTempbanned_title {
            get {
                return ResourceManager.GetString("ModerationEmbedTempbanned_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedTempmuted_title {
            get {
                return ResourceManager.GetString("ModerationEmbedTempmuted_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbed_fieldDurationName {
            get {
                return ResourceManager.GetString("ModerationEmbed_fieldDurationName", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedTempbannedDM_title {
            get {
                return ResourceManager.GetString("ModerationEmbedTempbannedDM_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbedTempmutedDM_title {
            get {
                return ResourceManager.GetString("ModerationEmbedTempmutedDM_title", resourceCulture);
            }
        }
        
        internal static string ModerationEmbed_fieldDurationValue {
            get {
                return ResourceManager.GetString("ModerationEmbed_fieldDurationValue", resourceCulture);
            }
        }
    }
}
