//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finder.Bot.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PollLocale {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PollLocale() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Finder.Bot.Resources.PollLocale", typeof(PollLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PollError_alreadyVoted {
            get {
                return ResourceManager.GetString("PollError_alreadyVoted", resourceCulture);
            }
        }
        
        internal static string PollVoted {
            get {
                return ResourceManager.GetString("PollVoted", resourceCulture);
            }
        }
        
        internal static string PollDefaultOption2 {
            get {
                return ResourceManager.GetString("PollDefaultOption2", resourceCulture);
            }
        }
        
        internal static string PollDefaultOption1 {
            get {
                return ResourceManager.GetString("PollDefaultOption1", resourceCulture);
            }
        }
        
        internal static string PollEmbed_desc {
            get {
                return ResourceManager.GetString("PollEmbed_desc", resourceCulture);
            }
        }
    }
}
