//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finder.Bot.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TicketsLocale {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TicketsLocale() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Finder.Bot.Resources.TicketsLocale", typeof(TicketsLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TicketsError_noName {
            get {
                return ResourceManager.GetString("TicketsError_noName", resourceCulture);
            }
        }
        
        internal static string TicketsError_nameTooLong {
            get {
                return ResourceManager.GetString("TicketsError_nameTooLong", resourceCulture);
            }
        }
        
        internal static string TicketsPrefix {
            get {
                return ResourceManager.GetString("TicketsPrefix", resourceCulture);
            }
        }
        
        internal static string TicketsButton_closeBtn {
            get {
                return ResourceManager.GetString("TicketsButton_closeBtn", resourceCulture);
            }
        }
        
        internal static string TicketsButton_claimBtn {
            get {
                return ResourceManager.GetString("TicketsButton_claimBtn", resourceCulture);
            }
        }
        
        internal static string TicketsEmbed_title {
            get {
                return ResourceManager.GetString("TicketsEmbed_title", resourceCulture);
            }
        }
        
        internal static string TicketsEmbed_fieldValue {
            get {
                return ResourceManager.GetString("TicketsEmbed_fieldValue", resourceCulture);
            }
        }
        
        internal static string TicketsEmbedCreated_fieldValue {
            get {
                return ResourceManager.GetString("TicketsEmbedCreated_fieldValue", resourceCulture);
            }
        }
        
        internal static string TicketsError_notTicket {
            get {
                return ResourceManager.GetString("TicketsError_notTicket", resourceCulture);
            }
        }
        
        internal static string TicketsError_notOwner {
            get {
                return ResourceManager.GetString("TicketsError_notOwner", resourceCulture);
            }
        }
        
        internal static string TicketsClosed {
            get {
                return ResourceManager.GetString("TicketsClosed", resourceCulture);
            }
        }
        
        internal static string TicketsError_noPermission {
            get {
                return ResourceManager.GetString("TicketsError_noPermission", resourceCulture);
            }
        }
        
        internal static string TicketsError_alreadyClaimed {
            get {
                return ResourceManager.GetString("TicketsError_alreadyClaimed", resourceCulture);
            }
        }
        
        internal static string TicketsEmbedClaim_title {
            get {
                return ResourceManager.GetString("TicketsEmbedClaim_title", resourceCulture);
            }
        }
        
        internal static string TicketsEmbedClaim_fieldName {
            get {
                return ResourceManager.GetString("TicketsEmbedClaim_fieldName", resourceCulture);
            }
        }
        
        internal static string TicketsClaimed {
            get {
                return ResourceManager.GetString("TicketsClaimed", resourceCulture);
            }
        }
        
        internal static string TicketsError_notClaimed {
            get {
                return ResourceManager.GetString("TicketsError_notClaimed", resourceCulture);
            }
        }
        
        internal static string TicketsEmbedUnclaim_title {
            get {
                return ResourceManager.GetString("TicketsEmbedUnclaim_title", resourceCulture);
            }
        }
        
        internal static string TicketsUnclaimed {
            get {
                return ResourceManager.GetString("TicketsUnclaimed", resourceCulture);
            }
        }
        
        internal static string TicketsError_notMember {
            get {
                return ResourceManager.GetString("TicketsError_notMember", resourceCulture);
            }
        }
        
        internal static string TicketsError_alreadyMember_user {
            get {
                return ResourceManager.GetString("TicketsError_alreadyMember_user", resourceCulture);
            }
        }
        
        internal static string TicketsEmbedAddUser_title {
            get {
                return ResourceManager.GetString("TicketsEmbedAddUser_title", resourceCulture);
            }
        }
        
        internal static string TicketsEmbedAddUser_fieldName {
            get {
                return ResourceManager.GetString("TicketsEmbedAddUser_fieldName", resourceCulture);
            }
        }
        
        internal static string TicketsUserAdded {
            get {
                return ResourceManager.GetString("TicketsUserAdded", resourceCulture);
            }
        }
        
        internal static string TicketsError_notMember_user {
            get {
                return ResourceManager.GetString("TicketsError_notMember_user", resourceCulture);
            }
        }
        
        internal static string TicketsEmbedRemoveUser_title {
            get {
                return ResourceManager.GetString("TicketsEmbedRemoveUser_title", resourceCulture);
            }
        }
        
        internal static string TicketsEmbedRemoveUser_fieldName {
            get {
                return ResourceManager.GetString("TicketsEmbedRemoveUser_fieldName", resourceCulture);
            }
        }
        
        internal static string TicketsUserRemoved {
            get {
                return ResourceManager.GetString("TicketsUserRemoved", resourceCulture);
            }
        }
        
        internal static string TicketsClosedCancel {
            get {
                return ResourceManager.GetString("TicketsClosedCancel", resourceCulture);
            }
        }
        
        internal static string TicketsEmbedCloseConfirm_title {
            get {
                return ResourceManager.GetString("TicketsEmbedCloseConfirm_title", resourceCulture);
            }
        }
        
        internal static string TicketsEmbedCloseConfirm_fieldName {
            get {
                return ResourceManager.GetString("TicketsEmbedCloseConfirm_fieldName", resourceCulture);
            }
        }
        
        internal static string TicketsEmbedCloseConfirm_fieldValue {
            get {
                return ResourceManager.GetString("TicketsEmbedCloseConfirm_fieldValue", resourceCulture);
            }
        }
        
        internal static string TicketsEmbedCreated_title {
            get {
                return ResourceManager.GetString("TicketsEmbedCreated_title", resourceCulture);
            }
        }
        
        internal static string TicketsEmbedUnclaim_fieldName {
            get {
                return ResourceManager.GetString("TicketsEmbedUnclaim_fieldName", resourceCulture);
            }
        }
    }
}
