//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finder.Bot.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TicTacToeLocale {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TicTacToeLocale() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Finder.Bot.Resources.TicTacToeLocale", typeof(TicTacToeLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TicTacToeError_userBot {
            get {
                return ResourceManager.GetString("TicTacToeError_userBot", resourceCulture);
            }
        }
        
        internal static string TicTacToeError_self {
            get {
                return ResourceManager.GetString("TicTacToeError_self", resourceCulture);
            }
        }
        
        internal static string TicTacToeInvite {
            get {
                return ResourceManager.GetString("TicTacToeInvite", resourceCulture);
            }
        }
        
        internal static string TicTacToeReady {
            get {
                return ResourceManager.GetString("TicTacToeReady", resourceCulture);
            }
        }
        
        internal static string TicTacToeStarting {
            get {
                return ResourceManager.GetString("TicTacToeStarting", resourceCulture);
            }
        }
        
        internal static string TicTacToeEmbed_title {
            get {
                return ResourceManager.GetString("TicTacToeEmbed_title", resourceCulture);
            }
        }
        
        internal static string TicTacToeEmbed_fieldName {
            get {
                return ResourceManager.GetString("TicTacToeEmbed_fieldName", resourceCulture);
            }
        }
        
        internal static string TicTacToeEmbed_fieldValue_wait {
            get {
                return ResourceManager.GetString("TicTacToeEmbed_fieldValue_wait", resourceCulture);
            }
        }
        
        internal static string TicTacToeMessage {
            get {
                return ResourceManager.GetString("TicTacToeMessage", resourceCulture);
            }
        }
        
        internal static string TicTacToeCancelled {
            get {
                return ResourceManager.GetString("TicTacToeCancelled", resourceCulture);
            }
        }
        
        internal static string TicTacToeWin {
            get {
                return ResourceManager.GetString("TicTacToeWin", resourceCulture);
            }
        }
        
        internal static string TicTacToeDraw {
            get {
                return ResourceManager.GetString("TicTacToeDraw", resourceCulture);
            }
        }
        
        internal static string TicTacToeConfirm {
            get {
                return ResourceManager.GetString("TicTacToeConfirm", resourceCulture);
            }
        }
        
        internal static string TicTacToeChannelTopic {
            get {
                return ResourceManager.GetString("TicTacToeChannelTopic", resourceCulture);
            }
        }
    }
}
